spring.application.name=tool-calling-app

server.port=8081

#openai config
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini

logging.level.org.springframework.ai.chat.client.advisor=DEBUG
logging.level.org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor=DEBUG

app.weather.api-key=2f0ff142f2064ee6a7483928260905